#!/bin/bash

# test-metadata-generator.sh
# Test metadata.json generator

set -o nounset
set -o errexit
set -o pipefail

# 测试参数
TEST_CLUSTER_NAME="test-cluster"
TEST_REGION="us-east-1"
TEST_INFRA_ID="test-cluster-abc123"
TEST_CLUSTER_ID="12345678-1234-1234-1234-123456789012"
TEST_OUTPUT_DIR="./test-cleanup"

echo "🧪 Testing metadata.json generator..."
echo

# 清理之前的测试文件
rm -rf "$TEST_OUTPUT_DIR"

echo "📋 Test parameters:"
echo "  Cluster name: $TEST_CLUSTER_NAME"
echo "  AWS region: $TEST_REGION"
echo "  Infrastructure ID: $TEST_INFRA_ID"
echo "  Cluster ID: $TEST_CLUSTER_ID"
echo "  Output directory: $TEST_OUTPUT_DIR"
echo

# Test full-featured version
echo "🔧 Testing full-featured version..."
if ./generate-metadata-for-destroy.sh \
  -c "$TEST_CLUSTER_NAME" \
  -r "$TEST_REGION" \
  -i "$TEST_INFRA_ID" \
  -u "$TEST_CLUSTER_ID" \
  -o "$TEST_OUTPUT_DIR"; then
    echo "✅ Full-featured version test passed"
else
    echo "❌ Full-featured version test failed"
    exit 1
fi

echo

# Validate generated files
echo "🔍 Validating generated files..."
if [[ -f "$TEST_OUTPUT_DIR/metadata.json" ]]; then
    echo "✅ metadata.json file exists"
    
    # 验证 JSON 格式
    if jq empty "$TEST_OUTPUT_DIR/metadata.json" 2>/dev/null; then
        echo "✅ JSON format is valid"
    else
        echo "❌ JSON format is invalid"
        exit 1
    fi
    
    # 验证必需字段
    local required_fields=("clusterName" "clusterID" "infraID" "aws.region" "aws.identifier")
    local all_fields_valid=true
    
    for field in "${required_fields[@]}"; do
        if jq -e ".$field" "$TEST_OUTPUT_DIR/metadata.json" > /dev/null 2>&1; then
            echo "✅ Field '$field' exists"
        else
            echo "❌ Field '$field' is missing"
            all_fields_valid=false
        fi
    done
    
    if [[ "$all_fields_valid" == true ]]; then
        echo "✅ All required fields are present"
    else
        echo "❌ Some required fields are missing"
        exit 1
    fi
    
    # 显示生成的内容
    echo
    echo "📄 Generated metadata.json content:"
    cat "$TEST_OUTPUT_DIR/metadata.json" | jq .
    
else
    echo "❌ metadata.json file does not exist"
    exit 1
fi

echo

# Clean up test files
rm -rf "$TEST_OUTPUT_DIR"

# Test simplified version
echo "🔧 Testing simplified version..."
if ./quick-generate-metadata.sh "$TEST_CLUSTER_NAME" "$TEST_REGION" "$TEST_INFRA_ID" "$TEST_CLUSTER_ID" "$TEST_OUTPUT_DIR"; then
    echo "✅ Simplified version test passed"
else
    echo "❌ Simplified version test failed"
    exit 1
fi

echo

# Validate files generated by simplified version
echo "🔍 Validating files generated by simplified version..."
if [[ -f "$TEST_OUTPUT_DIR/metadata.json" ]]; then
    echo "✅ metadata.json file exists"
    
    # 验证 JSON 格式
    if jq empty "$TEST_OUTPUT_DIR/metadata.json" 2>/dev/null; then
        echo "✅ JSON format is valid"
    else
        echo "❌ JSON format is invalid"
        exit 1
    fi
    
    # 显示生成的内容
    echo
    echo "📄 Generated metadata.json content:"
    cat "$TEST_OUTPUT_DIR/metadata.json" | jq .
    
else
    echo "❌ metadata.json file does not exist"
    exit 1
fi

echo

# 清理测试文件
rm -rf "$TEST_OUTPUT_DIR"

echo "🎉 All tests passed!"
echo
echo "📋 Usage examples:"
echo "  # Full-featured version"
echo "  ./generate-metadata-for-destroy.sh -c \"my-cluster\" -r \"us-east-1\" -i \"my-cluster-abc123\" -u \"12345678-1234-1234-1234-123456789012\""
echo
echo "  # Simplified version"
echo "  ./quick-generate-metadata.sh \"my-cluster\" \"us-east-1\" \"my-cluster-abc123\" \"12345678-1234-1234-1234-123456789012\""
echo
echo "  # Destroy cluster"
echo "  cd cleanup"
echo "  openshift-install destroy cluster --dir . --log-level debug"
